name: WebdriverIO Tests with Allure Report

on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "18"

            - name: Install Dependencies
              run: npm install

            - name: Run WebdriverIO Tests
              run: npm run wdio
              continue-on-error: true

            - name: Generate Allure Report
              run: |
                  npm install -g allure-commandline
                  mkdir -p allure-results
                  cp -r ./test-results/* ./allure-results/
                  allure generate allure-results --clean -o allure-report
              continue-on-error: true

            - name: Commit and Push Allure Report
              run: |
                  git config --local user.email "actions@github.com"
                  git config --local user.name "GitHub Actions"
                  git checkout -b report
                  git add .
                  git commit -m "Add Allure Report"
                  git push origin report
