export default {
	mainLink: "https://telnyx.com/",
	globalCoverageLink: "https://telnyx.com/global-coverage",
	globalCoverageTitle: "Global coverage",
	contactUsLink: "https://telnyx.com/contact-us",
	contactUsTitle: "Talk to an expert",
	solutionsLink: "https://telnyx.com/solutions",
	developersLink: "https://developers.telnyx.com",
	portalLink: "https://portal.telnyx.com/",
	solutionsTitle: "Solutions for scaling your business",
	smsApiLink: "https://telnyx.com/products/sms-api",
	mmsApiLink: "https://telnyx.com/products/mms-api",
	mmsApiText: "MMS API",
	pricingLink: "https://telnyx.com/pricing/messaging",
	pricingTitle: "Messaging API pricing",
	customerStoriesLink: "https://telnyx.com/customer-stories/pointblank-political-campaign-sms",
	pointBlankPoliticalTitle: "Point Blank Political",
	reportAbuseLink: "https://telnyx.com/report-abuse",
	reportAbuseTitle: "Report Abuse",
	contactUsTitle: "Talk to an expert",
	whyTelnyxLink: "https://telnyx.com/why-telnyx",
	whyTelnyxTitle: "Helping you connect—your way",
	hyperlocalEdgeLink: "https://telnyx.com/resources/about-edge-connectivity",
	hyperlocalEdgeTitle: "Running on the edge: Everything you need to know",
	signUpLink: "https://telnyx.com/sign-up",
	signUpTitle: "Create a Telnyx account",
	missionControlLink: "https://telnyx.com/mission-control",
	missionControlTitle: "Mission Control Portal",
};
